export const textColor = '#5F7483'
export const textColorDark = '#424F5C'
export const textColorLight = '#E4E9EC'
export const blue = '#00B0F1'
export const lightBlue = '#32C5FF'
export const white = '#FFFFFF'
export const input = '#C9D4DB'
export const orange = '#FFEAD9'
export const green = '#50B83C'
export const grey = '#F4F6F8'
export const notification = '#FF8D26'
export const red = '#F21500'
export const  border_Blue = '#EBEBEB'
export const  border_Grey = '#F1F1F1'

